CREATE TABLE IF NOT EXISTS users
(
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  password VARCHAR(60) NOT NULL,
  state SMALLINT DEFAULT 1,
  PRIMARY KEY(id)
);